# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icough', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
